-- This analysis evaluates year-over-year (YoY) employee performance,
-- comparing revenue generated by each employee between 2003 and 2004.

WITH yoy_employees AS
(
	SELECT 
        t1.employeeNumber, 
        t1.firstName, 
        t1.lastName, 
        t1.jobTitle, 
        
        t5.officeCode, 
        t5.city, 
        t5.country,

	    YEAR(t3.orderdate) as year,

        -- Total revenue generated by each employee per year
	    SUM(t4.quantityOrdered * t4.priceEach) AS employee_revenue,
        
        -- Number of distinct orders handled
	    COUNT(DISTINCT t3.orderNumber) AS total_orders
        
	FROM employees t1

        -- Link employees to their customers
		INNER JOIN customers t2
			ON t1.employeeNumber = t2.salesRepEmployeeNumber
            
        -- Join office data
		INNER JOIN offices t5 
			ON t1.officeCode = t5.officeCode
            
        -- Join customer orders
		INNER JOIN orders t3
			ON t2.customerNumber = t3.customerNumber
            
        -- Join order details to calculate revenue
		INNER JOIN orderdetails t4 
			ON t3.orderNumber = t4.orderNumber

	WHERE 
        -- Filter for 2003–2004 period
        YEAR(t3.orderdate) >= '2003-01-01' AND
        YEAR(t3.orderDate) < '2005-01-01'AND
		t3.status = 'Shipped'

	GROUP BY 
        t1.employeeNumber, 
        t1.firstName, 
        t1.lastName, 
        t1.jobTitle, 
        t5.officeCode, 
        t5.city, 
        t5.country, 
        year 
), 

previous_revenue_cte AS
(
	SELECT
        employeeNumber, 
        firstName, 
        lastName, 
        city, 
        country, 
        jobTitle, 
        total_orders, 
        year, 
        employee_revenue,

        -- Window function:
        -- LAG retrieves the previous year's revenue for each employee
        -- PARTITION BY ensures comparison is done per employee
        -- ORDER BY defines chronological sequence
		LAG(employee_revenue) 
            OVER (PARTITION BY employeeNumber ORDER BY year) 
            AS previous_revenue
            
	FROM yoy_employees 
    
    -- Ordering for readability (does not affect window calculation)
	ORDER BY employeeNumber, year
), 
		
YoY_cte AS 
(
	SELECT *,
    
        -- Year-over-Year growth calculation per employee
        ROUND(
            (employee_revenue - previous_revenue) / previous_revenue * 100, 
        2) AS YoY_growth
        
	FROM previous_revenue_cte
)

SELECT * 
FROM YoY_cte

-- Allows comparison of each employee across years
ORDER BY employeeNumber, year;