-- This analysis evaluates office-level performance for 2003,
-- ranking offices based on generated revenue and analyzing their contribution
-- to total company revenue, including Pareto distribution.

WITH top_offices AS
(
SELECT 
    t1.city,

    -- Total revenue generated by each office
    SUM(t5.quantityOrdered * priceEach) as office_revenue_2003,
    
    -- Number of distinct orders handled per office
    COUNT(DISTINCT t4.orderNumber) AS total_orders

FROM offices t1

    -- Link offices to employees
	INNER JOIN employees t2 
		ON t1.officeCode = t2.officeCode
        
    -- Link employees to their customers
	INNER JOIN customers t3
        ON t2.employeeNumber = t3.salesRepEmployeeNumber
        
    -- Join customer orders
	INNER JOIN orders t4 
        ON t4.customerNumber = t3.customerNumber
        
    -- Join order details to compute revenue
	INNER JOIN orderdetails t5 
        ON t5.orderNumber = t4.orderNumber

WHERE 
    -- Filter only shipped orders in 2003
    YEAR(t4.orderDate) IN (2003) 
    AND t4.status = 'Shipped'

GROUP BY 
    t1.city
)

SELECT 

    -- Rank offices based on revenue (highest first)
    ROW_NUMBER() OVER (ORDER BY office_revenue_2003 DESC) as rank_count,

    city, 
    office_revenue_2003, 
    total_orders,

    -- Average revenue per order per office
    ROUND(office_revenue_2003 / total_orders, 2) AS avg_order_value,

    -- Share of total company revenue by office
    ROUND(
        office_revenue_2003 / SUM(office_revenue_2003) OVER() * 100, 
    2) AS revenue_percentage,

    -- Cumulative contribution (Pareto analysis)
    -- Helps identify which offices generate the majority of revenue
    ROUND(
        SUM(office_revenue_2003) OVER (ORDER BY office_revenue_2003 DESC) 
        / SUM(office_revenue_2003) OVER () * 100,
    2) AS pareto_cumulative_percentage

FROM top_offices

-- Display top-performing offices first
ORDER BY office_revenue_2003 DESC;