-- This analysis evaluates office-level performance for 2004,
-- ranking offices based on generated revenue and measuring their contribution
-- to total company revenue, including Pareto distribution.

WITH top_offices AS
(
SELECT 
    t1.city,

    -- Total revenue generated by each office
    SUM(t5.quantityOrdered * priceEach) as office_revenue_2004,
    
    -- Number of distinct orders handled per office
    COUNT(DISTINCT t4.orderNumber) AS total_orders

FROM offices t1

    -- Link offices to employees
	INNER JOIN employees t2 
		ON t1.officeCode = t2.officeCode
        
    -- Link employees to customers
	INNER JOIN customers t3
        ON t2.employeeNumber = t3.salesRepEmployeeNumber
        
    -- Join customer orders
	INNER JOIN orders t4 
        ON t4.customerNumber = t3.customerNumber
        
    -- Join order details to compute revenue
	INNER JOIN orderdetails t5 
        ON t5.orderNumber = t4.orderNumber

WHERE 
    -- Filter only shipped orders in 2004
    YEAR(t4.orderDate) IN (2004) 
    AND t4.status = 'Shipped'

GROUP BY 
    t1.city
)

SELECT 

    -- Rank offices by revenue (descending)
    ROW_NUMBER() OVER (ORDER BY office_revenue_2004 DESC) as rank_count,

    city, 
    office_revenue_2004, 
    total_orders,

    -- Average revenue per order per office
    ROUND(office_revenue_2004 / total_orders, 2) AS avg_order_value,

    -- Share of total company revenue
    ROUND(
        office_revenue_2004 / SUM(office_revenue_2004) OVER() * 100, 
    2) AS revenue_percentage,

    -- Cumulative revenue contribution (Pareto analysis)
    ROUND(
        SUM(office_revenue_2004) OVER (ORDER BY office_revenue_2004 DESC) 
        / SUM(office_revenue_2004) OVER () * 100,
    2) AS pareto_cumulative_percentage

FROM top_offices

-- Display top-performing offices first
ORDER BY office_revenue_2004 DESC;