-- List of all employees and their assigned office location
-- This provides a reference view of the organizational structure
SELECT 
    t1.employeeNumber, 
    t1.reportsTo, 
    t1.jobTitle, 
    t1.firstName, 
    t1.lastName, 
    t1.officeCode, 
    t2.city, 
    t2.country 
FROM employees t1

-- Join to enrich employee data with office location
INNER JOIN offices t2
    ON t1.officeCode = t2.officeCode;

----------------------------------------------------------------------------------------------------------------------------------

-- This analysis evaluates employee performance based on generated revenue in 2003.
-- It ranks employees and highlights their contribution to total company revenue,
-- including cumulative contribution to identify Pareto distribution (80/20 effect).

WITH employees_performance_03 AS
(
SELECT 
    t1.employeeNumber, 
    t1.firstName, 
    t1.lastName, 
    t1.jobTitle, 
    
    t5.officeCode, 
    t5.city, 
    t5.country,

    YEAR(t3.orderdate) as year,

    -- Total revenue generated by each employee
    SUM(t4.quantityOrdered * t4.priceEach) AS employee_revenue,
    
    -- Number of distinct orders handled
    COUNT(DISTINCT t3.orderNumber) AS total_orders

FROM employees t1

    -- Link employees to their customers
	INNER JOIN customers t2
		ON t1.employeeNumber = t2.salesRepEmployeeNumber
        
    -- Join office information
	INNER JOIN offices t5 
        ON t1.officeCode = t5.officeCode
        
    -- Join orders placed by customers
	INNER JOIN orders t3
		ON t2.customerNumber = t3.customerNumber
        
    -- Join order details to compute revenue
	INNER JOIN orderdetails t4 
		ON t3.orderNumber = t4.orderNumber

WHERE 
    -- Filter only shipped orders in 2003
    YEAR(t3.orderdate) >= '2003-01-01' AND
    YEAR(t3.orderDate) < '2004-01-01'AND
    t3.status = 'Shipped'

GROUP BY 
    t1.employeeNumber, 
    t1.firstName, 
    t1.lastName, 
    t1.jobTitle, 
    t5.officeCode, 
    t5.city, 
    t5.country, 
    year 
) 

SELECT 

    -- Rank employees based on total revenue (highest first)
    ROW_NUMBER() OVER (ORDER BY employee_revenue DESC) AS rank_count,

    firstName, 
    lastName, 
    city, 
    country, 
    jobTitle, 
    employee_revenue, 
    total_orders,

    -- Average revenue per order handled by the employee
    ROUND(employee_revenue / total_orders, 2) AS avg_order_value,

    -- Percentage contribution to total company revenue
    ROUND(employee_revenue / SUM(employee_revenue) OVER() * 100, 2) AS revenue_percentage,

    -- Cumulative revenue contribution (Pareto analysis)
    -- Orders employees by revenue and accumulates their contribution
    ROUND(
        SUM(employee_revenue) OVER (ORDER BY employee_revenue DESC) 
        / SUM(employee_revenue) OVER () * 100,
    2) AS pareto_cumulative_percentage

FROM employees_performance_03

-- Display highest-performing employees first
ORDER BY employee_revenue DESC;