-- This analysis evaluates year-over-year (YoY) office performance,
-- comparing revenue generated by each office between 2003 and 2004
-- to identify geographical growth patterns.

WITH yoy_offices AS
(
SELECT 
    t1.city,
    
    YEAR(t4.orderDate) as year,

    -- Total revenue generated per office per year
    SUM(t5.quantityOrdered * priceEach) as office_revenue

FROM offices t1

    -- Link offices to employees
	INNER JOIN employees t2 
		ON t1.officeCode = t2.officeCode
        
    -- Link employees to customers
	INNER JOIN customers t3
        ON t2.employeeNumber = t3.salesRepEmployeeNumber
        
    -- Join customer orders
	INNER JOIN orders t4 
        ON t4.customerNumber = t3.customerNumber
        
    -- Join order details to compute revenue
	INNER JOIN orderdetails t5 
        ON t5.orderNumber = t4.orderNumber

WHERE 
    -- Filter analysis period (2003–2004)
    YEAR(t4.orderDate) IN (2003, 2004) 
    AND t4.status = 'Shipped'

GROUP BY 
    t1.city, 
    year
),

previous_revenue AS
(
	SELECT 
        city, 
        year, 
        office_revenue,

        -- Window function:
        -- LAG retrieves previous year's revenue for each office
        -- PARTITION BY city ensures comparison per office
        -- ORDER BY year defines chronological order
	    LAG(office_revenue) 
            OVER (PARTITION BY city ORDER BY year) 
            AS previous_revenue
            
	FROM yoy_offices
),

YoY_offices_growth AS
(
	SELECT *,
    
        -- Year-over-Year growth calculation at office level
	    ROUND(
            (office_revenue - previous_revenue) / previous_revenue * 100, 
        2) AS YoY_growth
        
	FROM previous_revenue
)

SELECT * 
FROM YoY_offices_growth

-- Allows comparison of each office across years
ORDER BY city, year;